#!/usr/bin/python

target_dict = {'LH2': {'targpos': 1,
                       'density': 4.242e22,
                       'length': 49.077,
                       'layers': 1,
                       'A': 1,
                       'scale': (4.242e22 * 49.077 * 1 * 1)},
               'LD2': {'targpos': 3,
                       'density': 4.835e22,
                       'length': 48.002,
                       'layers': 1,
                       'A': 2,
                       'scale': (4.835e22 * 48.002 * 1 * 2)},
               'Fe': {'targpos': 5,
                      'density': 8.492e22,
                      'length': 0.6,
                      'layers': 3,
                      'A': 56,
                      'scale': (8.492e22 * 0.6 * 3 * 56)},
               'C': {'targpos': 6,
                     'density': 9.035e22,
                     'length': 1.069,
                     'layers': 3,
                     'A': 12,
                     'scale': (9.035e22 * 1.069 * 3 * 12)},
               'W': {'targpos': 7,
                     'density': 6.322e22,
                     'length': 0.3028,
                     'layers': 3,
                     'A': 183,
                     'scale': (6.322e22 * 0.3028 * 3 * 183)},
               'None': {'targpos': 4,
                        'density': None,
                        'length': None,
                        'layers': None,
                        'A': None,
                        'scale': None},
               'Empty': {'targpos': 2,
                        'density': None,
                        'length': None,
                        'layers': None,
                        'A': None,
                        'scale': None}}

