#!/usr/bin/python

target_dict = {'LH2': {'targpos': 1,
                       'density': 4.32e22,
                       'length': 50.8,
                       'layers': 1,
                       'A': 1,
                       'scale': (4.32e22 * 50.8 * 1 * 1)},
               'LD2': {'targpos': 3,
                       'density': 5.06e22,
                       'length': 50.8,
                       'layers': 1,
                       'A': 2,
                       'scale': (5.06e22 * 50.8 * 1 * 2)},
               'Fe': {'targpos': 5,
                      'density': 8.49e22,
                      'length': 0.635,
                      'layers': 3,
                      'A': 56,
                      'scale': (8.49e22 * 0.635 * 3 * 56)},
               'C': {'targpos': 6,
                     'density': 9.035e22,
                     'length': 1.10744,
                     'layers': 3,
                     'A': 12,
                     'scale': (9.035e22 * 1.10744 * 3 * 12)},
               'W': {'targpos': 7,
                     'density': 6.32e22,
                     'length': 0.3175,
                     'layers': 3,
                     'A': 183,
                     'scale': (6.32e22 * 0.3175 * 3 * 183)},
               'None': {'targpos': 4,
                        'density': None,
                        'length': None,
                        'layers': None,
                        'A': None,
                        'scale': None},
               'Empty': {'targpos': 2,
                        'density': None,
                        'length': None,
                        'layers': None,
                        'A': None,
                        'scale': None}}

